export { default as Home } from './Dashboard.tsx'
export { default as Error } from './Error'
export { default as Auth } from './Auth'
export { default as Profile } from './Profile'
export { default as NpcPage } from './Npc'
export { default as DialogPage } from './Dialogs'
export { default as QuestPage } from './Quests'
export { default as MainPage } from './MainPage.tsx'
export { default as UserAgreementPage } from './UserAgreement.tsx'
export { default as Settings } from './Settings.tsx'
export { default as UserProfile } from './UserProfile.tsx'

